const apiBase='/harness-api/v1';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const pct=v=>`${num(v).toFixed(1)}%`;
let controlState={enabled:false,mode:'observe',stake:1,autoLiquidate:true,sl:-8.34,tp:100,liveExecution:false,serverLive:false,liveBlocked:false};
let controlDirty=false;
let controlsBound=false;
const compactTime=v=>{if(!v)return'--';const d=new Date(v);return Number.isNaN(d.valueOf())?String(v):d.toLocaleTimeString('es-MX',{hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'});};
async function api(path,opts={}){const r=await fetch(`${apiBase}${path}`,{credentials:'same-origin',cache:'no-store',headers:{'content-type':'application/json',...(opts.headers||{})},...opts});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data;}
const get=path=>api(path);
const patch=(path,body)=>api(path,{method:'PATCH',body:JSON.stringify(body)});
const post=(path,body)=>api(path,{method:'POST',body:JSON.stringify(body)});
function etClock(){return new Date().toLocaleTimeString('es-MX',{timeZone:'America/New_York',hour12:false})+' ET';}
function sideOf(row){return String(row?.side||row?.signal||row?.preferred_side||'NONE').toUpperCase();}
function intervalOf(row){const raw=String(row?.interval||row?.indicators?.candidate?.interval||'').toLowerCase();return raw.includes('15')?'15m':raw.includes('5')?'5m':raw||'--';}
function statusOf(row){return String(row?.status||row?.transaction_status||row?.execution||'pending').toLowerCase();}
function asConfidence(row){let v=num(row?.probability ?? row?.confidence ?? row?.indicators?.candidate?.probability ?? row?.indicators?.candidate?.confidence,0);if(v<=1)v*=100;return Math.max(0,Math.min(100,v));}
function statusLabel(auto){if(!auto.enabled||auto.status==='stopped')return'DETENIDO';const mode=String(auto.mode||'observe').toLowerCase();const liveExecution=auto.live_execution_enabled===true;if(auto.live_blocked||auto.status==='blocked'||(mode==='live'&&!liveExecution))return'LIVE BLOQUEADO';return `${mode.toUpperCase()} ${String(auto.status||'sync').toUpperCase()}`;}
function setSaveState(text){$('controlSaveState').textContent=text;$('saveControls').disabled=!controlDirty;}
function liveGateHint(){if(controlState.mode!=='live')return' La ejecucion LIVE real solo aplica cuando el modo es Live.';if(!controlState.serverLive)return' El servidor no tiene habilitado POLYMARKET_LIVE_TRADING_ENABLED.';if(!controlState.liveExecution)return' Segundo candado apagado: analiza senales, pero rechaza ordenes reales.';return' Segundo candado encendido: Live puede ejecutar ordenes reales con las reglas activas.';}
function syncControlSummary(){const gate=liveGateHint();$('rulesNote').textContent=`SL: $${controlState.stake} baja a $${(controlState.stake*(1+controlState.sl/100)).toFixed(2)}. TP: $${controlState.stake} sube a $${(controlState.stake*(1+controlState.tp/100)).toFixed(2)} o mas.${gate}`;}
function applyLiveGateAvailability(){const liveToggle=$('liveExecutionEnabled');const canUse=controlState.mode==='live'&&controlState.serverLive;liveToggle.disabled=!canUse;if(!canUse){liveToggle.checked=false;controlState.liveExecution=false;}document.querySelector('.live-gate')?.classList.toggle('disabled',!canUse);}
function readControls(){return {enabled:$('tradingEnabled').checked,mode:$('tradingMode').value,stake:controlState.stake,autoLiquidate:$('autoLiquidate').checked,sl:num($('stopLossPct').value,-8.34),tp:num($('takeProfitPct').value,100),liveExecution:$('tradingMode').value==='live'&&$('liveExecutionEnabled').checked};}
function markControlsDirty(){const current=readControls();controlState={...controlState,...current,liveBlocked:false};applyLiveGateAvailability();syncStakeButtons();syncControlSummary();controlDirty=true;setSaveState('SIN GUARDAR');}
function syncStakeButtons(){[...$('stakeGroup').querySelectorAll('button')].forEach(b=>b.classList.toggle('active',Number(b.dataset.stake)===controlState.stake));}
function syncControls(auto,rules={}){if(controlDirty)return;controlState={enabled:!!auto.enabled,mode:auto.mode||rules.mode||'observe',stake:num(auto.polymarket_stake_usdt??rules.polymarket_stake_usdt,1),autoLiquidate:auto.polymarket_auto_liquidate_enabled??rules.polymarket_auto_liquidate_enabled??true,sl:num(auto.polymarket_stop_loss_pct??rules.polymarket_stop_loss_pct,-8.34),tp:num(auto.polymarket_take_profit_pct??rules.polymarket_take_profit_pct,100),liveExecution:!!(auto.live_execution_enabled??rules.live_execution_enabled),serverLive:!!(auto.server_live_trading_enabled??rules.server_live_trading_enabled),liveBlocked:!!(auto.live_blocked||auto.status==='blocked'||((auto.mode||rules.mode)==='live'&&!(auto.live_execution_enabled??rules.live_execution_enabled)))};$('tradingEnabled').checked=controlState.enabled;$('tradingMode').value=controlState.mode;$('autoLiquidate').checked=controlState.autoLiquidate;$('stopLossPct').value=controlState.sl;$('takeProfitPct').value=controlState.tp;$('liveExecutionEnabled').checked=controlState.liveExecution;syncStakeButtons();applyLiveGateAvailability();setSaveState(controlState.liveBlocked?'LIVE BLOQUEADO':(controlState.enabled?'LISTO':'DETENIDO'));syncControlSummary();}
function controlPayload(){const current=readControls();return {enabled:current.enabled,mode:current.mode,live_execution_enabled:current.liveExecution,polymarket_stake_usdt:current.stake,polymarket_auto_liquidate_enabled:current.autoLiquidate,polymarket_stop_loss_pct:current.sl,polymarket_take_profit_pct:current.tp};}
function bindControls(){if(controlsBound)return;controlsBound=true;$('stakeGroup').addEventListener('click',e=>{const b=e.target.closest('button[data-stake]');if(!b)return;controlState.stake=Number(b.dataset.stake);markControlsDirty();});['tradingEnabled','tradingMode','liveExecutionEnabled','autoLiquidate','stopLossPct','takeProfitPct'].forEach(id=>$(id).addEventListener('change',markControlsDirty));$('saveControls').disabled=true;$('saveControls').addEventListener('click',async()=>{const body=controlPayload();if(body.mode==='live'&&body.enabled&&body.live_execution_enabled&&!confirm('Vas a activar ejecucion LIVE real para Polymarket. Esto puede enviar ordenes reales. ¿Confirmas?'))return;$('saveControls').disabled=true;$('controlSaveState').textContent='GUARDANDO';try{const payload=await patch('/automations/paper-trading',body);controlDirty=false;syncControls(payload.automation||{},payload.rules||{});$('controlSaveState').textContent='GUARDADO';setTimeout(refresh,400);}catch(e){controlDirty=true;$('saveControls').disabled=false;$('controlSaveState').textContent='ERROR';alert(`No se pudo guardar: ${e.message}`);}});}
function getCandidateRows(auto){const source=[...(auto?.orders||[]),...(auto?.observations||[])];const rows=[];for(const item of source){if(item?.candidate)rows.push({...item.candidate,_order:item});for(const c of (item?.candidates||item?.indicators?.candidates||[])){if(c&&typeof c==='object')rows.push({...c,_order:item});}}return rows.filter(r=>r.interval||r._order?.interval);}
function latestByInterval(auto,txs){const candidates=getCandidateRows(auto);const map={};for(const c of candidates){const key=intervalOf(c);if(key==='5m'||key==='15m')map[key]=c;}for(const tx of txs){const key=intervalOf(tx);if((key==='5m'||key==='15m')&&!map[key])map[key]={_order:tx,interval:key,preferred_side:sideOf(tx),confidence:asConfidence(tx)/100,probability:asConfidence(tx)/100,passes_filters:sideOf(tx)!=='NONE',window_et:tx.window,reason:tx.risk,status:tx.status};}return ['5m','15m'].map(key=>map[key]||{interval:key,preferred_side:'NONE',confidence:0,probability:0,passes_filters:false,reason:'Esperando lectura del siguiente ciclo'});}
function windowCard(row){const order=row._order||{};const micro=row.microstructure||order.microstructure||{};const conf=asConfidence(row)||asConfidence(order);const side=String(row.preferred_side||sideOf(order)||'NONE');const sideClass=side.toLowerCase().includes('up')?'up':side.toLowerCase().includes('down')?'down':'none';const edge=num(row.edge,0)*100;const ask=num(micro.ask ?? order.price,0);const status=row.passes_filters?'trade':'no-trade';const reason=(row.reasons&&row.reasons.join(', '))||order.reason||row.reason||order.risk||(row.passes_filters?'Pasa filtros de confianza, edge y microestructura':'No cumple filtros del ciclo');const fill=Math.max(8,Math.min(100,conf));return `<article class="window-card ${status}"><div class="window-top"><div><div class="window-title">${esc(row.interval||'--')}</div><small class="muted">${esc(row.window_et||order.window_et||order.window||'Ventana actual')}</small></div><span class="window-side ${sideClass}">${esc(side)}</span></div><div class="confidence-ring" style="--value:${fill}"><span>${pct(conf)}</span></div><div class="window-stats"><div class="stat-box"><small>Ask</small><strong>${ask?ask.toFixed(2):'--'}</strong></div><div class="stat-box"><small>Edge</small><strong>${edge?`${edge.toFixed(2)}%`:'--'}</strong></div><div class="stat-box"><small>Estado</small><strong>${row.passes_filters?'TRADE':'NO TRADE'}</strong></div></div><div class="countdown"><span style="width:${fill}%"></span></div><div class="window-reason">${esc(reason)}</div></article>`;}
function renderWindows(auto,txs){const rows=latestByInterval(auto,txs);$('windowGrid').innerHTML=rows.map(windowCard).join('');$('watchingBadge').textContent=`${rows.filter(r=>r.passes_filters).length}/2 LISTAS`;}
function renderTop(auto,txs){const orders=txs.filter(tx=>sideOf(tx)!=='NONE');const wins=orders.filter(tx=>statusOf(tx)==='won').length;const losses=orders.filter(tx=>statusOf(tx)==='lost').length;const open=orders.filter(tx=>statusOf(tx)==='accepted').length;const rejected=orders.filter(tx=>statusOf(tx)==='rejected').length;const pnl=txs.reduce((sum,tx)=>sum+num(tx.pnl||tx.pnl_paper,0),0);const guards=[...(auto.position_actions||[]),...(auto.claim_actions||[])];const label=statusLabel(auto);$('modeChip').textContent=label;$('engineMode').textContent=label;$('lastRun').textContent=compactTime(auto.last_run_at);$('clockEt').textContent=etClock();$('topStatus').textContent=label;$('netPnl').textContent=money(pnl);$('pnlTotal').textContent=money(pnl);$('openCount').textContent=open;$('winRate').textContent=pct((wins/(wins+losses||1))*100);$('rejectedCount').textContent=rejected;$('guardCount').textContent=guards.length;$('pnlCaption').textContent=`${orders.length} operaciones revisadas`;}
function orderTitle(tx){return `${intervalOf(tx)} · ${sideOf(tx)} · ${tx.market||'BTC Up/Down'}`;}
function liquidationPayload(tx){const c=(tx.indicators||{}).candidate||{};const m=c.microstructure||{};return {token_id:tx.token_id||m.token_id||tx.asset,shares:tx.size||tx.shares,current_price:tx.current_price||tx.price};}
async function liquidateTrade(tx){const payload=liquidationPayload(tx);try{await post('/automations/paper-trading/liquidate',payload);alert('Liquidacion enviada.');refresh();}catch(e){alert(`No se pudo liquidar: ${e.message}`);}}
function renderOrders(txs){const orders=txs.filter(tx=>sideOf(tx)!=='NONE').slice(0,14);$('orderList').innerHTML=orders.map((tx,i)=>{const st=statusOf(tx);const detail=tx.execution_error||tx.risk||tx.reason||tx.window||'';const lp=liquidationPayload(tx);const blocked=st==='rejected'||st==='live_blocked'||tx.execution==='live_blocked'||st==='no_trade';const canLiquidate=!blocked&&st==='accepted'&&lp.token_id&&lp.shares&&lp.current_price;const actionLabel=canLiquidate?'Liquidar':(blocked?'Sin posicion':'Liquidar');window.__polyOrders=orders;return `<div class="order-row"><div class="order-main"><strong>${esc(orderTitle(tx))}</strong><small>${esc(detail)}</small><small>${esc(tx.window||tx.timestamp||'')}</small></div><div class="order-money"><b>${money(tx.stake_usdt)}</b><span class="badge ${esc(st)}">${esc(st)}</span><button class="mini-action" ${canLiquidate?'':'disabled'} onclick="liquidateTrade(window.__polyOrders[${i}])">${actionLabel}</button></div></div>`;}).join('')||'<div class="empty">Sin ordenes recientes para Polymarket.</div>';}
function renderGuards(auto){const actions=[...(auto.position_actions||[]),...(auto.claim_actions||[])];$('guardBadge').textContent=actions.length?`${actions.length} ACTIVAS`:'AUTO';$('guardList').innerHTML=actions.map(a=>{const st=statusOf(a);const title=a.action==='claim_profit'?'Cobro de ganancia':(String(a.action||'').includes('stop_loss')?'Stop loss':'Take profit');const meta=[a.outcome,a.size?`${a.size} shares`:null,a.current_price?`precio ${a.current_price}`:null,a.cash_pnl?`PnL ${money(a.cash_pnl)}`:null,a.threshold_pct?`umbral ${a.threshold_pct}%`:null].filter(Boolean);const note=a.note||a.error||a.market||'';return `<div class="guard-row"><div><strong>${esc(title)}</strong><small>${esc(note)}</small><div class="guard-meta">${meta.map(x=>`<span class="badge">${esc(x)}</span>`).join('')}</div></div><span class="badge ${esc(st)}">${esc(st)}</span></div>`;}).join('')||'<div class="empty">Sin SL/TP ni cobros pendientes en el ultimo ciclo.</div>';}
function renderActivity(auto,txs){const events=[];for(const tx of txs.slice(0,24))events.push({time:tx.timestamp,label:orderTitle(tx),status:statusOf(tx),detail:tx.risk||tx.window||''});for(const c of (auto.recent_cycles||[]).slice().reverse())events.push({time:c.created_at,label:`Ciclo ${c.mode||''}`,status:c.errors_count?'error':'ok',detail:`${c.orders_count||0} ordenes · ${c.observations_count||0} observaciones`});events.sort((a,b)=>new Date(b.time||0)-new Date(a.time||0));$('activityCount').textContent=`${events.length} eventos`;$('activityLog').innerHTML=events.slice(0,18).map(e=>`<div class="activity-row"><div><strong>${esc(e.label)}</strong><small>${esc(e.detail)}</small></div><div><span class="activity-status">${esc(e.status)}</span><small>${compactTime(e.time)}</small></div></div>`).join('')||'<div class="empty">Sin actividad reciente.</div>';}
function drawPnl(txs){const c=$('pnlCanvas');const ctx=c.getContext('2d');const w=c.width,h=c.height;ctx.clearRect(0,0,w,h);const values=[0];txs.slice().reverse().forEach(tx=>values.push(values.at(-1)+num(tx.pnl||tx.pnl_paper,0)));const min=Math.min(...values,0),max=Math.max(...values,1);ctx.fillStyle='#ffffff';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#e3ecef';ctx.lineWidth=1;for(let i=0;i<6;i++){const y=24+i*(h-52)/5;ctx.beginPath();ctx.moveTo(28,y);ctx.lineTo(w-28,y);ctx.stroke();}ctx.beginPath();values.forEach((v,i)=>{const x=28+i*(w-56)/Math.max(values.length-1,1);const y=h-28-((v-min)/(max-min||1))*(h-64);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});const grad=ctx.createLinearGradient(0,0,w,0);grad.addColorStop(0,'#00a66a');grad.addColorStop(.65,'#1967d2');grad.addColorStop(1,'#b36b00');ctx.strokeStyle=grad;ctx.lineWidth=4;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke();ctx.fillStyle='#687780';ctx.font='13px Space Mono';ctx.fillText(`max ${money(max)}`,32,22);ctx.fillText(`min ${money(min)}`,32,h-10);}
async function refresh(){bindControls();try{const [autoPayload,txPayload,rulesPayload]=await Promise.all([get('/automations/paper-trading'),get('/agents/transactions?limit=220'),get('/agents/rules')]);const auto=autoPayload.automation||{};syncControls(auto,rulesPayload||{});const txs=(txPayload.transactions||[]).filter(tx=>String(tx.venue||'').toLowerCase()==='polymarket');renderTop(auto,txs);renderWindows(auto,txs);renderOrders(txs);renderGuards(auto);renderActivity(auto,txs);drawPnl(txs);}catch(e){$('windowGrid').innerHTML=`<div class="empty">No fue posible cargar Polymarket: ${esc(e.message)}</div>`;}}
refresh();setInterval(()=>{$('clockEt').textContent=etClock();},1000);setInterval(refresh,5000);
