const apiBase='/harness-api/v1';
const $=id=>document.getElementById(id);
let txState=[], latestStatus=null, latestAutomation={}, latestLogs={agents:{}}, txSignature='', txLoading=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const money=v=>num(v).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const plainMoney=v=>num(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
async function get(path){const r=await fetch(`${apiBase}${path}`,{credentials:'same-origin',cache:'no-store'});const ct=r.headers.get('content-type')||'';if(!r.ok)throw new Error(`HTTP ${r.status}`);return ct.includes('json')?r.json():r.text();}
function compactTime(value){if(!value)return'--';const d=new Date(value);return Number.isNaN(d.valueOf())?String(value):d.toLocaleString('es-MX',{hour12:false,month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'});}
function nowEt(){return new Date().toLocaleString('es-MX',{timeZone:'America/New_York',hour12:false,month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'})+' ET';}
function marketInterval(tx){const raw=String(tx?.interval||tx?.indicators?.candidate?.interval||'').toLowerCase();return raw.includes('15')?'15m':raw.includes('5')?'5m':raw||'--';}
function marketSymbol(tx){const interval=marketInterval(tx);return interval==='--'?'BTC-UP-DOWN':`BTC-UP-DOWN_${interval}`;}
function marketWindowEt(tx){return tx.window||tx.indicators?.candidate?.window_et||'';}
function compactEtWindow(value){if(!value)return'';const parts=String(value).split(' - ');const fmt=p=>{const m=String(p||'').match(/(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2})(?::\d{2})?\s+(E[DS]T)/);return m?`${m[1]} ${m[2]} ${m[3]}`:p;};return parts.length>1?`${fmt(parts[0])} - ${fmt(parts[1]).replace(/^\d{4}-\d{2}-\d{2}\s+/,'')}`:fmt(value);}
function txTime(tx){return String(tx.venue||'').toLowerCase()==='polymarket'?compactEtWindow(marketWindowEt(tx)):compactTime(tx.timestamp);}
function priceToBeat(tx){return tx.indicators?.price_to_beat_reference??tx.indicators?.candidate?.price_to_beat_reference??tx.price_to_beat_reference??tx.price;}
function predictedPrice(tx){return tx.indicators?.forecast_price_at_close??tx.indicators?.candidate?.forecast_price_at_close??tx.forecast_price_at_close;}
function closePrice(tx){return tx.indicators?.final_price_reference??tx.indicators?.candidate?.final_price_reference??tx.final_price_reference;}
function tableMoney(value){const n=Number(value);return Number.isFinite(n)&&n!==0?n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'--';}
function confidence(tx){return num(tx.confidence||tx.probability,0);}
function normalizeSide(tx){const side=String(tx.side||tx.signal||'NONE').toUpperCase();return ['UP','DOWN','NONE'].includes(side)?side:'NONE';}
function statusOf(tx){return String(tx.status||'pending').toLowerCase();}
function outcomeLabel(tx){const status=statusOf(tx), side=normalizeSide(tx), actual=String(tx.indicators?.winning_side||tx.indicators?.actual_close_side||'').toUpperCase();if(status==='rejected')return {label:'Rechazada / No enviada',klass:'rejected'};if(actual){if(side==='NONE')return {label:`Cerro ${actual} · Sin trade`,klass:'pending'};return side===actual?{label:`Cerro ${actual} · Acierto`,klass:'won'}:{label:`Cerro ${actual} · Error`,klass:'lost'};}if(status==='won')return {label:'Acierto',klass:'won'};if(status==='lost')return {label:'Error',klass:'lost'};if(status==='no_trade'||side==='NONE')return {label:'Pendiente / Sin trade',klass:'pending'};return {label:'Pendiente',klass:'pending'};}
function tradeReason(tx){if(statusOf(tx)==='rejected'&&(tx.execution_error||tx.indicators?.execution_error))return tx.execution_error||tx.indicators.execution_error;const cand=tx.indicators?.candidate||{};const labels={confidence_below_threshold:'Confianza por debajo del umbral',edge_too_small:'Edge o Kelly insuficiente',missing_ask:'Sin ask en order book',spread_too_wide:'Spread alto',insufficient_ask_depth:'Profundidad baja',too_close_to_close:'Cierre muy cercano',missing_side:'Sin direccion',duplicate_window_trade:'Ya existe trade en ventana',coordinator_blocked:'Sin evento valido',no_event_passed_filters:'Sin evento valido',kelly_or_stake_zero:'Kelly o stake en cero'};const reasons=cand.reasons||[];if(reasons.length)return reasons.map(r=>labels[r]||r).join(' · ');return labels[tx.risk]||tx.risk||'--';}
function autoCandidateRows(auto={}){const source=[...(auto.orders||[]),...(auto.observations||[])], rows=[];for(const item of source){if(item?.candidate)rows.push({...item.candidate,_order:item});for(const c of (item?.candidates||item?.indicators?.candidates||[])){if(c&&typeof c==='object')rows.push({...c,_order:item});}}return rows.filter(r=>r.interval||r._order?.interval);}
function autoInterval(row){const raw=String(row?.interval||row?._order?.interval||'').toLowerCase();return raw.includes('15')?'15m':raw.includes('5')?'5m':raw||'--';}
function autoWindow(row){return row.window_et||row._order?.window_et||row._order?.window||'';}
function autoConfidence(row){let v=num(row.probability??row.confidence??row._order?.probability,0);if(v<=1)v*=100;return Math.max(0,Math.min(100,v));}
function autoSide(row){return String(row.preferred_side||row._order?.preferred_side||row._order?.side||'NONE').toUpperCase();}
function autoHasFreshCycle(auto={}){return auto.enabled!==false&&String(auto.status||'').toLowerCase()!=='stopped'&&num(auto.last_age_seconds,999999)<=300;}
function autoSignalRows(auto={}){if(!autoHasFreshCycle(auto))return ['5m','15m'].map(key=>({interval:key,preferred_side:'NONE',confidence:0,passes_filters:false,reason:'Automatizacion detenida o sin ciclo vigente'}));const map={};for(const row of autoCandidateRows(auto)){const key=autoInterval(row);if(key==='5m'||key==='15m')map[key]=row;}return ['5m','15m'].map(key=>map[key]||{interval:key,preferred_side:'NONE',confidence:0,passes_filters:false,reason:'Sin lectura vigente del ultimo ciclo'});}
function kpi(label,value,klass=''){return `<div class="kpi ${klass}"><small>${esc(label)}</small><strong>${esc(value)}</strong></div>`;}
function autoState(auto={}){const enabled=auto.enabled===true;return enabled?(auto.status||'running'):'stopped';}
function autoMode(auto={}){return String(auto.enabled===false?'observe':(auto.mode||'observe')).toUpperCase();}
function renderKpis(payload,txPayload,auto={}){const s=payload.summary||{}, ts=txPayload.summary||{};$('kpis').innerHTML=[kpi('Health',s.health_score??100,'primary'),kpi('Trading',autoState(auto)),kpi('Modo',autoMode(auto)),kpi('Stake',money(auto.polymarket_stake_usdt??1)),kpi('SL / TP',`${num(auto.polymarket_time_stop_pct,75).toFixed(0)}% / ${num(auto.polymarket_take_profit_pct,100).toFixed(0)}%`),kpi('PnL',money(ts.pnl||s.total_pnl||0))].join('');$('sessionStatus').textContent=`Validation ${s.health_score??'--'} health · ${autoMode(auto)}`;}
function laneCard({title,subtitle,status='slot',stats=[],active=false}){return `<article class="lane-card ${active?'active':'ready'}"><div class="lane-top"><div><div class="lane-title">${esc(title)}</div><div class="lane-sub">${esc(subtitle)}</div></div><span class="badge ${esc(status)}">${esc(status)}</span></div><div class="lane-stats">${stats.map(([a,b])=>`<div class="mini-stat"><small>${esc(a)}</small><strong>${esc(b)}</strong></div>`).join('')}</div></article>`;}
function renderLanes(payload,txPayload,auto={}){const agents=payload.agents||[], discovery=payload.discovery||{}, summary=txPayload.summary||{};const lanes=[];for(const a of agents){lanes.push({title:a.name||a.agent,subtitle:`${a.market||'strategy'} · ${a.timeframe||'runtime'}`,status:a.agent==='paper_trading'?autoMode(auto).toLowerCase():(a.mode||a.status),active:true,stats:[['Status',a.agent==='paper_trading'?autoState(auto):(a.status||'--')],['Signal',a.signal||a.prediction||'NONE'],['Conf',`${num(a.confidence).toFixed(1)}%`]]});}
if(payload.ocean){lanes.push({title:'OCEAN',subtitle:'Orquestador cognitivo multiagente',status:payload.ocean.status==='ok'?'ok':'error',active:payload.ocean.status==='ok',stats:[['Status',payload.ocean.status||'--'],['Agentes',payload.ocean.agents_count??0],['LLM',payload.ocean.local_llm?'local':'--']]});}
lanes.push({title:'Polymarket BTC',subtitle:'5m y 15m validation actual',status:autoMode(auto).toLowerCase(),active:auto.enabled!==false,stats:[['Estado',autoState(auto)],['Stake',money(auto.polymarket_stake_usdt??1)],['Mode',autoMode(auto)]]});
lanes.push({title:'MEXC Spot',subtitle:'Espacio reservado para trades spot',status:'slot',stats:[['Estado','ready'],['Filtro','RSI/MACD'],['Owner','trader']]});
lanes.push({title:'Dexter Research',subtitle:'Espacio para research coordinado',status:'slot',stats:[['Estado','ready'],['Rol','research'],['Salida','tesis']]});
lanes.push({title:'CRON externo',subtitle:`${(discovery.crons||[]).length} crons descubiertos`,status:'slot',stats:[['Crons',(discovery.crons||[]).length],['Procesos',(discovery.processes||[]).length],['Docker',(discovery.docker||[]).length]]});
$('laneCount').textContent=`${lanes.length} lanes`;$('lanes').innerHTML=lanes.map(laneCard).join('');}
function renderWindows(){const rows=autoSignalRows(latestAutomation);let active=0;$('windowGrid').innerHTML=rows.map(row=>{const conf=autoConfidence(row), hasSignal=Boolean(autoWindow(row)||row.reason||row._order?.reason), signal=hasSignal?(row.passes_filters?'trade':'no_trade'):'waiting', cls=row.passes_filters?'good':(hasSignal?'warn':'warn');if(row.passes_filters)active++;return `<article class="window-card ${cls}"><div class="window-top"><div><div class="window-title">${esc(autoInterval(row))}</div><div class="window-meta">${esc(compactEtWindow(autoWindow(row))||'sin ventana vigente')}</div></div><span class="badge ${esc(signal)}">${esc(signal==='trade'?'senal trade':signal==='no_trade'?'no trade':'sin dato')}</span></div><div class="lane-stats"><div class="mini-stat"><small>Senal</small><strong>${esc(autoSide(row))}</strong></div><div class="mini-stat"><small>Confianza</small><strong>${conf.toFixed(1)}%</strong></div><div class="mini-stat"><small>Posiciones</small><strong>${num(latestAutomation.polymarket_open_positions?.length,0)}</strong></div></div><div class="progress"><span style="width:${Math.max(6,conf)}%"></span></div><div class="reason">${esc(row.reason||row._order?.reason||'Sin lectura vigente del ultimo ciclo')}</div></article>`;}).join('');$('windowStatus').textContent=`${active}/2 senales`;}
function renderEvidence(auto={}){const rows=autoSignalRows(auto);$('evidenceStatus').textContent=`${rows.filter(r=>autoWindow(r)).length} ventanas`;const configRow=`<div class="evidence-row"><div><strong>Estado actual · ${esc(autoMode(auto))}</strong><small>Trading ${esc(autoState(auto))} · Stake ${esc(money(auto.polymarket_stake_usdt??1))} · SL ventana ${esc(num(auto.polymarket_time_stop_pct,75).toFixed(0))}% · TP ${esc(num(auto.polymarket_take_profit_pct,100).toFixed(0))}% · abiertas ${esc(num(auto.polymarket_open_positions?.length,0))}</small></div><span class="badge ${auto.enabled===false?'stopped':'running'}">${esc(autoState(auto))}</span></div>`;const signalRows=rows.map(row=>`<div class="evidence-row"><div><strong>${esc(autoInterval(row))} · ${esc(autoSide(row))}</strong><small>${esc(compactEtWindow(autoWindow(row))||'sin ventana vigente')} · ${esc(row.reason||row._order?.reason||'sin lectura vigente')}</small></div><span class="badge ${row.passes_filters?'accepted':'no_trade'}">${row.passes_filters?'senal trade':'no trade'}</span></div>`).join('');$('evidenceList').innerHTML=configRow+signalRows;}
function renderInfra(payload){const infra=payload.infrastructure||{}, gpu=(infra.gpu||[])[0]||{};$('generatedAt').textContent=compactTime(payload.generated_at);$('infra').innerHTML=[['CPU',`${infra.cpu_percent||0}%`],['RAM',`${infra.ram_percent||0}% · ${infra.ram_available_gb||0} GB libres`],['GPU',gpu.name?`${gpu.name} · ${gpu.memory_percent}% VRAM`:'N/D'],['Docker',`${(infra.docker||[]).length} contenedores`],['API latency',`${infra.api_latency_ms??0} ms`]].map(([a,b])=>`<div class="infra-row"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`).join('');}
function renderBottom(payload,logs){const alerts=payload.alerts||[];$('alertCount').textContent=alerts.length;$('alerts').innerHTML=(alerts.length?alerts:['Sin alertas criticas.']).map(a=>`<li>${esc(a)}</li>`).join('');const d=payload.discovery||{}, crons=d.crons||[], processes=d.processes||[], ocean=payload.ocean||{};$('discoveryCount').textContent=crons.length+processes.length+(ocean.status==='ok'?1:0);$('discovery').innerHTML=[['CRON detectados',crons.length],['Procesos relevantes',processes.length],['Docker containers',(d.docker||[]).length],['GPU devices',(d.gpu||[]).length],['OCEAN',ocean.status==='ok'?`${ocean.agents_count||0} agentes · online`:'sin respuesta'],['Slots nuevos','MEXC, Dexter, CRON externo']].map(([a,b])=>`<div class="discovery-row"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`).join('');const logText=Object.entries((logs||{}).agents||{}).map(([name,lines])=>`[${name}]\n${(lines||[]).slice(-34).join('\n')}`).join('\n\n')||'Sin logs registrados.';$('logs').textContent=logText;}
function optionSet(rows,key){return [...new Set(rows.map(x=>key==='status'?statusOf(x):key==='side'?normalizeSide(x):x[key]).filter(Boolean))].sort();}
function fillSelect(id,values,label){const el=$(id);const current=el.value;el.innerHTML=`<option value="">${label}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');el.value=values.includes(current)?current:'';}
function renderTransactionFilters(){const agents=optionSet(txState,'agent');$('agentFilter').closest('label')?.classList.toggle('hidden-filter',agents.length<=1);fillSelect('agentFilter',agents,'Todos');fillSelect('modeFilter',optionSet(txState,'mode'),'Todos');fillSelect('sideFilter',['UP','DOWN','NONE'],'Todos');fillSelect('statusFilter',optionSet(txState,'status'),'Todos');}
function renderTransactions(){const agent=$('agentFilter').value,mode=$('modeFilter').value,side=$('sideFilter').value,status=$('statusFilter').value;const rows=txState.filter(tx=>(!agent||tx.agent===agent)&&(!mode||tx.mode===mode)&&(!side||normalizeSide(tx)===side)&&(!status||statusOf(tx)===status));const exposure=rows.reduce((a,b)=>a+num(b.stake_usdt),0),pnl=rows.reduce((a,b)=>a+num(b.pnl),0),rejected=rows.filter(x=>statusOf(x)==='rejected').length,notrade=rows.filter(x=>statusOf(x)==='no_trade').length;$('txSummary').innerHTML=[['Rows',rows.length],['Exposure',money(exposure)],['PnL',money(pnl)],['Rejected',rejected],['No trade',notrade]].map(([a,b])=>`<div><small>${esc(a)}</small><strong>${esc(b)}</strong></div>`).join('');$('txHead').innerHTML='<tr><th>Hora ET</th><th>Agente</th><th>Venue</th><th>Mercado</th><th>Side</th><th>Mode</th><th>Status</th><th>Precio a superar</th><th>Predicho</th><th>Cierre</th><th>Stake</th><th>Confianza</th><th>Motivo</th><th>Resultado</th><th>PnL</th></tr>';$('transactions').innerHTML=rows.slice(0,180).map(tx=>{const st=statusOf(tx),side=normalizeSide(tx),out=outcomeLabel(tx);return `<tr class="mode-${esc(tx.mode)}"><td>${esc(txTime(tx))}</td><td>${esc(tx.agent||'--')}</td><td>${esc(tx.venue||'--')}</td><td>${esc(marketSymbol(tx))}</td><td><span class="side side-${esc(side.toLowerCase())}">${esc(side)}</span></td><td>${esc(tx.mode||'--')}</td><td><span class="badge ${esc(st)}">${esc(st)}</span></td><td>${tableMoney(priceToBeat(tx))}</td><td>${tableMoney(predictedPrice(tx))}</td><td>${tableMoney(closePrice(tx))}</td><td>${num(tx.stake_usdt).toLocaleString()}</td><td>${confidence(tx).toFixed(1)}%</td><td>${esc(tradeReason(tx))}</td><td><span class="badge ${esc(out.klass)}">${esc(out.label)}</span></td><td>${plainMoney(tx.pnl||0)}</td></tr>`;}).join('')||'<tr><td colspan="15">Sin transacciones registradas.</td></tr>';renderWindows();renderEvidence(latestAutomation);}
function txPayloadSignature(payload){return JSON.stringify(((payload||{}).transactions||[]).map(tx=>[tx.id,tx.timestamp,tx.window,tx.interval,tx.side,tx.status,tx.pnl,tx.stake_usdt,tx.risk,tx.execution_error,tx.indicators?.winning_side,tx.indicators?.final_price_reference,tx.indicators?.forecast_price_at_close]));}
function renderTransactionPayload(payload={},force=false){const next=txPayloadSignature(payload);if(!force&&next===txSignature)return;txSignature=next;txState=(payload.transactions||[]).filter(tx=>String(tx.venue||'').toLowerCase()==='polymarket');renderTransactionFilters();renderTransactions();if(latestStatus)renderKpis(latestStatus,payload,latestAutomation);if(latestStatus)renderLanes(latestStatus,payload,latestAutomation);}
async function refresh(){try{const [status,logs,txPayload,autoPayload,oceanPayload]=await Promise.all([get('/agents/status'),get('/agents/logs?limit=80').catch(e=>({agents:{validation:[`Logs no disponibles: ${e.message}`]}})),get('/agents/transactions?limit=220'),get('/automations/paper-trading'),get('/ocean/health').catch(e=>({status:'error',error:e.message,agents_count:0}))]);status.ocean=oceanPayload;latestStatus=status;latestAutomation=autoPayload.automation||{};latestLogs=logs;renderKpis(status,txPayload,latestAutomation);renderLanes(status,txPayload,latestAutomation);renderInfra(status);renderBottom(status,logs);renderTransactionPayload(txPayload,true);}catch(e){const msg=`No fue posible cargar validation: ${e.message}`;$('alerts').innerHTML=`<li>${esc(msg)}</li>`;$('logs').textContent=msg;$('kpis').innerHTML=[kpi('Health','N/D','primary'),kpi('Trading','N/D'),kpi('Modo','N/D'),kpi('Stake','N/D'),kpi('SL / TP','N/D'),kpi('PnL','N/D')].join('');}}
async function refreshTransactions(force=false){if(txLoading&&!force)return;txLoading=true;try{renderTransactionPayload(await get('/agents/transactions?limit=220'),force);}catch(e){$('alerts')?.insertAdjacentHTML('afterbegin',`<li>Transacciones no disponibles: ${esc(e.message)}</li>`);}finally{txLoading=false;}}
function msToNextFiveMinuteWindow(){const now=new Date();const elapsed=(now.getMinutes()%5)*60000+now.getSeconds()*1000+now.getMilliseconds();return Math.max(1000,300000-elapsed+1200);}
function scheduleWindowRefresh(){setTimeout(()=>{refreshTransactions(true);scheduleWindowRefresh();},msToNextFiveMinuteWindow());}
['agentFilter','modeFilter','sideFilter','statusFilter'].forEach(id=>document.addEventListener('change',e=>{if(e.target?.id===id)renderTransactions();}));
$('refreshBtn')?.addEventListener('click',()=>{const btn=$('refreshBtn');btn.disabled=true;btn.textContent='Actualizando';Promise.resolve(refresh()).finally(()=>setTimeout(()=>{btn.disabled=false;btn.textContent='Actualizar';},600));});
refresh();setInterval(refresh,30000);setInterval(()=>refreshTransactions(false),5000);scheduleWindowRefresh();
