const apiBase='/harness-api/v1';
const $=id=>document.getElementById(id);
let txState=[], latestStatus=null, latestLogs={agents:{}}, txSignature='', txLoading=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const money=v=>num(v).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const plainMoney=v=>num(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
async function get(path){const r=await fetch(`${apiBase}${path}`,{credentials:'same-origin',cache:'no-store'});const ct=r.headers.get('content-type')||'';if(!r.ok)throw new Error(`HTTP ${r.status}`);return ct.includes('json')?r.json():r.text();}
function compactTime(value){if(!value)return'--';const d=new Date(value);return Number.isNaN(d.valueOf())?String(value):d.toLocaleString('es-MX',{hour12:false,month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'});}
function nowEt(){return new Date().toLocaleString('es-MX',{timeZone:'America/New_York',hour12:false,month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'})+' ET';}
function marketInterval(tx){const raw=String(tx?.interval||tx?.indicators?.candidate?.interval||'').toLowerCase();return raw.includes('15')?'15m':raw.includes('5')?'5m':raw||'--';}
function marketSymbol(tx){const interval=marketInterval(tx);return interval==='--'?'BTC-UP-DOWN':`BTC-UP-DOWN_${interval}`;}
function marketWindowEt(tx){return tx.window||tx.indicators?.candidate?.window_et||'';}
function compactEtWindow(value){if(!value)return nowEt();const parts=String(value).split(' - ');const fmt=p=>{const m=String(p||'').match(/(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2})(?::\d{2})?\s+(E[DS]T)/);return m?`${m[1]} ${m[2]} ${m[3]}`:p;};return parts.length>1?`${fmt(parts[0])} - ${fmt(parts[1]).replace(/^\d{4}-\d{2}-\d{2}\s+/,'')}`:fmt(value);}
function txTime(tx){return String(tx.venue||'').toLowerCase()==='polymarket'?compactEtWindow(marketWindowEt(tx)):compactTime(tx.timestamp);}
function priceToBeat(tx){return tx.indicators?.price_to_beat_reference??tx.indicators?.candidate?.price_to_beat_reference??tx.price_to_beat_reference??tx.price;}
function predictedPrice(tx){return tx.indicators?.forecast_price_at_close??tx.indicators?.candidate?.forecast_price_at_close??tx.forecast_price_at_close;}
function closePrice(tx){return tx.indicators?.final_price_reference??tx.indicators?.candidate?.final_price_reference??tx.final_price_reference;}
function tableMoney(value){const n=Number(value);return Number.isFinite(n)&&n!==0?n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'--';}
function confidence(tx){return num(tx.confidence||tx.probability,0);}
function normalizeSide(tx){const side=String(tx.side||tx.signal||'NONE').toUpperCase();return ['UP','DOWN','NONE'].includes(side)?side:'NONE';}
function statusOf(tx){return String(tx.status||'pending').toLowerCase();}
function outcomeLabel(tx){const status=statusOf(tx), side=normalizeSide(tx), actual=String(tx.indicators?.winning_side||tx.indicators?.actual_close_side||'').toUpperCase();if(status==='rejected')return {label:'Rechazada / No enviada',klass:'rejected'};if(actual){if(side==='NONE')return {label:`Cerro ${actual} · Sin trade`,klass:'pending'};return side===actual?{label:`Cerro ${actual} · Acierto`,klass:'won'}:{label:`Cerro ${actual} · Error`,klass:'lost'};}if(status==='won')return {label:'Acierto',klass:'won'};if(status==='lost')return {label:'Error',klass:'lost'};if(status==='no_trade'||side==='NONE')return {label:'Pendiente / Sin trade',klass:'pending'};return {label:'Pendiente',klass:'pending'};}
function tradeReason(tx){if(statusOf(tx)==='rejected'&&(tx.execution_error||tx.indicators?.execution_error))return tx.execution_error||tx.indicators.execution_error;const cand=tx.indicators?.candidate||{};const labels={confidence_below_threshold:'Confianza por debajo del umbral',edge_too_small:'Edge o Kelly insuficiente',missing_ask:'Sin ask en order book',spread_too_wide:'Spread alto',insufficient_ask_depth:'Profundidad baja',too_close_to_close:'Cierre muy cercano',missing_side:'Sin direccion',duplicate_window_trade:'Ya existe trade en ventana',coordinator_blocked:'Sin evento valido',no_event_passed_filters:'Sin evento valido',kelly_or_stake_zero:'Kelly o stake en cero'};const reasons=cand.reasons||[];if(reasons.length)return reasons.map(r=>labels[r]||r).join(' · ');return labels[tx.risk]||tx.risk||'--';}
function kpi(label,value,klass=''){return `<div class="kpi ${klass}"><small>${esc(label)}</small><strong>${esc(value)}</strong></div>`;}
function renderKpis(payload,txPayload){const s=payload.summary||{}, ts=txPayload.summary||{};$('kpis').innerHTML=[kpi('Health',s.health_score??100,'primary'),kpi('Agentes',s.agents_total??0),kpi('Live',s.live??0),kpi('Rechazadas',ts.by_status?.rejected||0),kpi('Exposure',money(ts.exposure_usdt||0)),kpi('PnL',money(ts.pnl||s.total_pnl||0))].join('');$('sessionStatus').textContent=`Validation ${s.health_score??'--'} health`;}
function laneCard({title,subtitle,status='slot',stats=[],active=false}){return `<article class="lane-card ${active?'active':'ready'}"><div class="lane-top"><div><div class="lane-title">${esc(title)}</div><div class="lane-sub">${esc(subtitle)}</div></div><span class="badge ${esc(status)}">${esc(status)}</span></div><div class="lane-stats">${stats.map(([a,b])=>`<div class="mini-stat"><small>${esc(a)}</small><strong>${esc(b)}</strong></div>`).join('')}</div></article>`;}
function renderLanes(payload,txPayload){const agents=payload.agents||[], discovery=payload.discovery||{}, summary=txPayload.summary||{};const lanes=[];for(const a of agents){lanes.push({title:a.name||a.agent,subtitle:`${a.market||'strategy'} · ${a.timeframe||'runtime'}`,status:a.mode||a.status,active:true,stats:[['Status',a.status||'--'],['Signal',a.signal||a.prediction||'NONE'],['Conf',`${num(a.confidence).toFixed(1)}%`]]});}
lanes.push({title:'Polymarket BTC',subtitle:'5m y 15m live validation',status:'live',active:true,stats:[['Trades',summary.total||0],['PnL',money(summary.pnl||0)],['Mode','live']]});
lanes.push({title:'MEXC Spot',subtitle:'Espacio reservado para trades spot',status:'slot',stats:[['Estado','ready'],['Filtro','RSI/MACD'],['Owner','trader']]});
lanes.push({title:'Dexter Research',subtitle:'Espacio para research coordinado',status:'slot',stats:[['Estado','ready'],['Rol','research'],['Salida','tesis']]});
lanes.push({title:'CRON externo',subtitle:`${(discovery.crons||[]).length} crons descubiertos`,status:'slot',stats:[['Crons',(discovery.crons||[]).length],['Procesos',(discovery.processes||[]).length],['Docker',(discovery.docker||[]).length]]});
$('laneCount').textContent=`${lanes.length} lanes`;$('lanes').innerHTML=lanes.map(laneCard).join('');}
function latestWindowRows(){const map={};for(const tx of txState){const key=marketInterval(tx);if((key==='5m'||key==='15m')&&!map[key])map[key]=tx;}return ['5m','15m'].map(key=>map[key]||{interval:key,status:'waiting',side:'NONE',confidence:0,risk:'Esperando ciclo de validacion'});}
function renderWindows(){const rows=latestWindowRows();let active=0;$('windowGrid').innerHTML=rows.map(tx=>{const st=statusOf(tx), conf=Math.max(0,Math.min(100,confidence(tx)));const cls=st==='won'||st==='accepted'?'good':st==='rejected'||st==='lost'?'bad':'warn';if(normalizeSide(tx)!=='NONE')active++;return `<article class="window-card ${cls}"><div class="window-top"><div><div class="window-title">${esc(marketInterval(tx))}</div><div class="window-meta">${esc(txTime(tx))}</div></div><span class="badge ${esc(st)}">${esc(st)}</span></div><div class="lane-stats"><div class="mini-stat"><small>Side</small><strong>${esc(normalizeSide(tx))}</strong></div><div class="mini-stat"><small>Confianza</small><strong>${conf.toFixed(1)}%</strong></div><div class="mini-stat"><small>Stake</small><strong>${money(tx.stake_usdt||0)}</strong></div></div><div class="progress"><span style="width:${Math.max(6,conf)}%"></span></div><div class="reason">${esc(tradeReason(tx))}</div></article>`;}).join('');$('windowStatus').textContent=`${active}/2 trade`;}
function renderEvidence(){const rows=txState.slice(0,8);$('evidenceStatus').textContent=`${rows.length} rows`;$('evidenceList').innerHTML=rows.map(tx=>{const out=outcomeLabel(tx);return `<div class="evidence-row"><div><strong>${esc(marketSymbol(tx))} · ${esc(normalizeSide(tx))}</strong><small>${esc(tradeReason(tx))}</small></div><span class="badge ${esc(out.klass)}">${esc(out.label)}</span></div>`;}).join('')||'<div class="empty">Sin evidencia reciente.</div>';}
function renderInfra(payload){const infra=payload.infrastructure||{}, gpu=(infra.gpu||[])[0]||{};$('generatedAt').textContent=compactTime(payload.generated_at);$('infra').innerHTML=[['CPU',`${infra.cpu_percent||0}%`],['RAM',`${infra.ram_percent||0}% · ${infra.ram_available_gb||0} GB libres`],['GPU',gpu.name?`${gpu.name} · ${gpu.memory_percent}% VRAM`:'N/D'],['Docker',`${(infra.docker||[]).length} contenedores`],['API latency',`${infra.api_latency_ms??0} ms`]].map(([a,b])=>`<div class="infra-row"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`).join('');}
function renderBottom(payload,logs){const alerts=payload.alerts||[];$('alertCount').textContent=alerts.length;$('alerts').innerHTML=(alerts.length?alerts:['Sin alertas criticas.']).map(a=>`<li>${esc(a)}</li>`).join('');const d=payload.discovery||{}, crons=d.crons||[], processes=d.processes||[];$('discoveryCount').textContent=crons.length+processes.length;$('discovery').innerHTML=[['CRON detectados',crons.length],['Procesos relevantes',processes.length],['Docker containers',(d.docker||[]).length],['GPU devices',(d.gpu||[]).length],['Slots nuevos','MEXC, Dexter, CRON externo']].map(([a,b])=>`<div class="discovery-row"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`).join('');const logText=Object.entries((logs||{}).agents||{}).map(([name,lines])=>`[${name}]\n${(lines||[]).slice(-34).join('\n')}`).join('\n\n')||'Sin logs registrados.';$('logs').textContent=logText;}
function optionSet(rows,key){return [...new Set(rows.map(x=>key==='status'?statusOf(x):key==='side'?normalizeSide(x):x[key]).filter(Boolean))].sort();}
function fillSelect(id,values,label){const el=$(id);const current=el.value;el.innerHTML=`<option value="">${label}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');el.value=values.includes(current)?current:'';}
function renderTransactionFilters(){const agents=optionSet(txState,'agent');$('agentFilter').closest('label')?.classList.toggle('hidden-filter',agents.length<=1);fillSelect('agentFilter',agents,'Todos');fillSelect('modeFilter',optionSet(txState,'mode'),'Todos');fillSelect('sideFilter',['UP','DOWN','NONE'],'Todos');fillSelect('statusFilter',optionSet(txState,'status'),'Todos');}
function renderTransactions(){const agent=$('agentFilter').value,mode=$('modeFilter').value,side=$('sideFilter').value,status=$('statusFilter').value;const rows=txState.filter(tx=>(!agent||tx.agent===agent)&&(!mode||tx.mode===mode)&&(!side||normalizeSide(tx)===side)&&(!status||statusOf(tx)===status));const exposure=rows.reduce((a,b)=>a+num(b.stake_usdt),0),pnl=rows.reduce((a,b)=>a+num(b.pnl),0),rejected=rows.filter(x=>statusOf(x)==='rejected').length,notrade=rows.filter(x=>statusOf(x)==='no_trade').length;$('txSummary').innerHTML=[['Rows',rows.length],['Exposure',money(exposure)],['PnL',money(pnl)],['Rejected',rejected],['No trade',notrade]].map(([a,b])=>`<div><small>${esc(a)}</small><strong>${esc(b)}</strong></div>`).join('');$('txHead').innerHTML='<tr><th>Hora ET</th><th>Agente</th><th>Venue</th><th>Mercado</th><th>Side</th><th>Mode</th><th>Status</th><th>Precio a superar</th><th>Predicho</th><th>Cierre</th><th>Stake</th><th>Confianza</th><th>Motivo</th><th>Resultado</th><th>PnL</th></tr>';$('transactions').innerHTML=rows.slice(0,180).map(tx=>{const st=statusOf(tx),side=normalizeSide(tx),out=outcomeLabel(tx);return `<tr class="mode-${esc(tx.mode)}"><td>${esc(txTime(tx))}</td><td>${esc(tx.agent||'--')}</td><td>${esc(tx.venue||'--')}</td><td>${esc(marketSymbol(tx))}</td><td><span class="side side-${esc(side.toLowerCase())}">${esc(side)}</span></td><td>${esc(tx.mode||'--')}</td><td><span class="badge ${esc(st)}">${esc(st)}</span></td><td>${tableMoney(priceToBeat(tx))}</td><td>${tableMoney(predictedPrice(tx))}</td><td>${tableMoney(closePrice(tx))}</td><td>${num(tx.stake_usdt).toLocaleString()}</td><td>${confidence(tx).toFixed(1)}%</td><td>${esc(tradeReason(tx))}</td><td><span class="badge ${esc(out.klass)}">${esc(out.label)}</span></td><td>${plainMoney(tx.pnl||0)}</td></tr>`;}).join('')||'<tr><td colspan="15">Sin transacciones registradas.</td></tr>';renderWindows();renderEvidence();}
function txPayloadSignature(payload){return JSON.stringify(((payload||{}).transactions||[]).map(tx=>[tx.id,tx.timestamp,tx.window,tx.interval,tx.side,tx.status,tx.pnl,tx.stake_usdt,tx.risk,tx.execution_error,tx.indicators?.winning_side,tx.indicators?.final_price_reference,tx.indicators?.forecast_price_at_close]));}
function renderTransactionPayload(payload={},force=false){const next=txPayloadSignature(payload);if(!force&&next===txSignature)return;txSignature=next;txState=(payload.transactions||[]).filter(tx=>String(tx.venue||'').toLowerCase()==='polymarket');renderTransactionFilters();renderTransactions();if(latestStatus)renderKpis(latestStatus,payload);if(latestStatus)renderLanes(latestStatus,payload);}
async function refresh(){try{const [status,logs,txPayload]=await Promise.all([get('/agents/status'),get('/agents/logs?limit=80').catch(e=>({agents:{validation:[`Logs no disponibles: ${e.message}`]}})),get('/agents/transactions?limit=220')]);latestStatus=status;latestLogs=logs;renderKpis(status,txPayload);renderLanes(status,txPayload);renderInfra(status);renderBottom(status,logs);renderTransactionPayload(txPayload,true);}catch(e){const msg=`No fue posible cargar validation: ${e.message}`;$('alerts').innerHTML=`<li>${esc(msg)}</li>`;$('logs').textContent=msg;$('kpis').innerHTML=[kpi('Health','N/D','primary'),kpi('Agentes','N/D'),kpi('Live','N/D'),kpi('Rechazadas','N/D'),kpi('Exposure','N/D'),kpi('PnL','N/D')].join('');}}
async function refreshTransactions(force=false){if(txLoading&&!force)return;txLoading=true;try{renderTransactionPayload(await get('/agents/transactions?limit=220'),force);}catch(e){$('alerts')?.insertAdjacentHTML('afterbegin',`<li>Transacciones no disponibles: ${esc(e.message)}</li>`);}finally{txLoading=false;}}
function msToNextFiveMinuteWindow(){const now=new Date();const elapsed=(now.getMinutes()%5)*60000+now.getSeconds()*1000+now.getMilliseconds();return Math.max(1000,300000-elapsed+1200);}
function scheduleWindowRefresh(){setTimeout(()=>{refreshTransactions(true);scheduleWindowRefresh();},msToNextFiveMinuteWindow());}
['agentFilter','modeFilter','sideFilter','statusFilter'].forEach(id=>document.addEventListener('change',e=>{if(e.target?.id===id)renderTransactions();}));
$('refreshBtn')?.addEventListener('click',()=>{const btn=$('refreshBtn');btn.disabled=true;btn.textContent='Actualizando';Promise.resolve(refresh()).finally(()=>setTimeout(()=>{btn.disabled=false;btn.textContent='Actualizar';},600));});
refresh();setInterval(refresh,30000);setInterval(()=>refreshTransactions(false),5000);scheduleWindowRefresh();
