const FALLBACK_T=['BTC-USD','ETH-USD','AAPL','NVDA','SPY','TSLA','QQQ'],P=['1d','5d','7d','1mo','3mo','6mo','1y','2y','5y'],I=['1m','5m','15m','30m','1h','1d','1wk'];
const $=id=>document.getElementById(id); for(const [id,arr] of [['period',P],['interval',I]]) $(id).innerHTML=arr.map(x=>`<option>${x}</option>`).join(''); $('period').value='7d'; $('interval').value='5m';
let PORT_GROUPS={}, USER_ASSETS=[], ASSET_ROWS=[];
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderUserAssets(){ const set=new Set(USER_ASSETS); $('ticker').innerHTML=(USER_ASSETS.length?USER_ASSETS:FALLBACK_T).map(x=>`<option>${esc(x)}</option>`).join(''); $('assetPicker').innerHTML=Object.entries(PORT_GROUPS).map(([group,items])=>{const visible=items.filter(t=>set.has(t)); return visible.length?`<div class="asset-group"><h4>${esc(group)}</h4><div>${visible.map(t=>`<label class="asset-chip"><input type="checkbox" value="${esc(t)}" ${['HWM','PLTR','NVDA','V','AMZN','WM'].includes(t)?'checked':''}><span>${esc(t)}</span></label>`).join('')}</div></div>`:''}).join(''); const checked=[...document.querySelectorAll('#assetPicker input:checked')]; if(!checked.length){[...document.querySelectorAll('#assetPicker input')].slice(0,Math.min(6,USER_ASSETS.length)).forEach(x=>x.checked=true);} renderAssetAdmin(); }
function renderAssetAdmin(){ if(!$('assetRows'))return; const selected=new Set(ASSET_ROWS.map(a=>a.symbol)); if($('assetCount'))$('assetCount').textContent=`${ASSET_ROWS.length} activo${ASSET_ROWS.length===1?'':'s'}`; $('assetRows').innerHTML=ASSET_ROWS.map(a=>`<div class="asset-row" data-symbol="${esc(a.symbol)}"><input class="sym" value="${esc(a.symbol)}" aria-label="Ticker"><select class="typ" aria-label="Tipo">${['Acciones','Criptos','Divisas','Otros'].map(t=>`<option ${a.asset_type===t?'selected':''}>${t}</option>`).join('')}</select><input class="lab" value="${esc(a.label||'')}" placeholder="Nombre opcional" aria-label="Etiqueta"><button class="asset-mini asset-update" type="button">Guardar</button><button class="asset-mini asset-delete danger" type="button">Eliminar</button></div>`).join(''); $('assetUniverse').innerHTML=Object.entries(PORT_GROUPS).map(([g,items])=>`<div class="asset-group"><h4>${esc(g)}</h4><div>${items.map(t=>`<label class="asset-chip"><input type="checkbox" value="${esc(t)}" data-type="${esc(g)}" class="catalog-toggle" ${selected.has(t)?'checked':''}><span>${esc(t)}</span></label>`).join('')}</div></div>`).join(''); }
async function loadUserAssets(){ try{const d=await (await fetch('/auth/assets')).json(); PORT_GROUPS=d.catalog||{}; USER_ASSETS=d.selected||[]; ASSET_ROWS=d.assets||USER_ASSETS.map(symbol=>({symbol,asset_type:'Otros',label:symbol})); renderUserAssets();}catch(e){PORT_GROUPS={'Activos':FALLBACK_T}; USER_ASSETS=FALLBACK_T; ASSET_ROWS=FALLBACK_T.map(symbol=>({symbol,asset_type:'Otros',label:symbol})); renderUserAssets();}}
function assetMsg(text,isError=false){ if(!$('assetMsg'))return; $('assetMsg').textContent=text; $('assetMsg').className=isError?'asset-msg error':'asset-msg'; }
async function createAsset(symbol,type,label=''){const body={symbol:symbol||$('newSymbol').value,asset_type:type||$('newType').value,label:label||$('newLabel').value}; const r=await fetch('/auth/assets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const d=await r.json().catch(()=>({})); assetMsg(r.ok?'Ticker agregado':(d.error||'No se pudo agregar'),!r.ok); if(r.ok){if($('newSymbol'))$('newSymbol').value=''; if($('newLabel'))$('newLabel').value=''; await loadUserAssets();}}
async function updateAsset(old,row){const body={symbol:row.querySelector('.sym').value,asset_type:row.querySelector('.typ').value,label:row.querySelector('.lab').value}; const r=await fetch('/auth/assets/'+encodeURIComponent(old),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const d=await r.json().catch(()=>({})); assetMsg(r.ok?'Ticker actualizado':(d.error||'No se pudo actualizar'),!r.ok); if(r.ok)await loadUserAssets();}
async function deleteAsset(symbol){const r=await fetch('/auth/assets/'+encodeURIComponent(symbol),{method:'DELETE'}); const d=await r.json().catch(()=>({})); assetMsg(r.ok?'Ticker eliminado':(d.error||'No se pudo eliminar'),!r.ok); if(r.ok)await loadUserAssets();}
function selectedAssets(){return [...document.querySelectorAll('#assetPicker input:checked')].map(x=>x.value)}
loadUserAssets();
function openTickerModal(){if(!$('tickerModal'))return; $('tickerModal').classList.add('open'); $('tickerModal').setAttribute('aria-hidden','false'); document.body.classList.add('modal-open'); setTimeout(()=>{$('newSymbol')?.focus()},40);}
function closeTickerModal(){if(!$('tickerModal'))return; $('tickerModal').classList.remove('open'); $('tickerModal').setAttribute('aria-hidden','true'); document.body.classList.remove('modal-open');}
if($('openTickerAdmin'))$('openTickerAdmin').addEventListener('click',openTickerModal);
if($('closeTickerAdmin'))$('closeTickerAdmin').addEventListener('click',closeTickerModal);
document.addEventListener('click',e=>{if(e.target.matches('[data-close-ticker]'))closeTickerModal();});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeTickerModal();});
if($('assetCreate'))$('assetCreate').addEventListener('click',()=>createAsset());
if($('assetRefresh'))$('assetRefresh').addEventListener('click',loadUserAssets);
document.addEventListener('click',e=>{const row=e.target.closest('.asset-row'); if(e.target.classList.contains('asset-update')&&row)updateAsset(row.dataset.symbol,row); if(e.target.classList.contains('asset-delete')&&row)deleteAsset(row.dataset.symbol);});
document.addEventListener('change',e=>{if(e.target.classList.contains('catalog-toggle')){if(e.target.checked)createAsset(e.target.value,e.target.dataset.type,e.target.value); else deleteAsset(e.target.value);}});
$('endpoint').onchange=()=>syncSections($('endpoint').value); syncSections($('endpoint').value);
$('run').onclick=async()=>{const e=$('endpoint').value; let url='/api/'+e; if(e.includes('market')||e==='forecast/prophet'||e==='forecast/lstm'){const q=new URLSearchParams({ticker:$('ticker').value,period:$('period').value,interval:$('interval').value,mode:$('mode').value,style:$('style').value,forecast_mode:$('forecastMode').value}); url+='?'+q;} if(e==='portfolio/markowitz'){const tickers=selectedAssets(); if(tickers.length<2||tickers.length>10){$('status').className='api-status error'; $('status').textContent='Selecciona entre 2 y 10 activos'; return;} const q=new URLSearchParams({tickers:tickers.join(','),benchmark:$('benchmark').value,period:$('portfolioPeriod').value,mode:$('mode').value}); url+='?'+q;} $('status').className='api-status loading loader'; $('status').textContent='Consultando'; try{const r=await fetch(url); const data=await r.json(); if(!r.ok) throw new Error(data.error||'Error'); render(data); $('status').className='api-status'; $('status').textContent=`Respuesta OK · ${data.latency_ms??'—'} ms`; }catch(err){$('status').className='api-status error'; $('status').textContent=err.message;}}
function baseRender(d){$('json').textContent=JSON.stringify(d,null,2); const rows=d.data||[]; if(!rows.length){$('table').innerHTML='';return;} const cols=Object.keys(rows[0]); $('table').className=''; $('table-title').textContent='Tabla dinámica'; $('table').innerHTML='<thead><tr>'+cols.map(c=>`<th>${c}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>`<td>${r[c]??''}</td>`).join('')+'</tr>').join('')+'</tbody>';}
const chartTheme={paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font:{color:'#a9b7c6',family:'Space Mono, monospace'},margin:{l:48,r:18,t:18,b:36},xaxis:{gridcolor:'rgba(255,255,255,.06)',rangeslider:{visible:false}},yaxis:{gridcolor:'rgba(255,255,255,.06)'},showlegend:false}; const plotCfg={displaylogo:false,responsive:true};
function n(rows,key){return rows.map(r=>r[key]==null?null:+r[key]);} function fmt(v){return v==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:2})} function pct(v){return v==null?'—':`${v>=0?'+':''}${Number(v* (Math.abs(v)<=3?100:1)).toFixed(2)}%`} function pctRaw(v){return v==null?'—':`${v>=0?'+':''}${Number(v).toFixed(2)}%`}
function renderMarket(d){baseRender(d); const m=d.metrics||{}; $('metrics').innerHTML=[['Modo',d.mode],['Filas',d.rows],['Último',fmt(m.last)],['Cambio %',pctRaw(m.change_pct)],['RSI',fmt(m.rsi)],['VWAP',fmt(m.vwap)],['Latencia ms',d.latency_ms]].map(([k,v])=>`<div class="api-metric"><span>${k}</span><b>${v??'—'}</b></div>`).join(''); const rows=d.data||[]; if(!rows.length||!window.Plotly)return; const x=rows.map(r=>r.Datetime||r.Date), open=n(rows,'Open'), high=n(rows,'High'), low=n(rows,'Low'), close=n(rows,'Close'), vol=n(rows,'Volume'); Plotly.react('candles',[{type:'candlestick',x,open,high,low,close,increasing:{line:{color:'#00ff99'}},decreasing:{line:{color:'#ff4466'}},name:'OHLC',yaxis:'y'},{type:'scatter',mode:'lines',x,y:n(rows,'SMA20'),line:{color:'#f6c344',width:1.4},name:'SMA20',yaxis:'y'},{type:'scatter',mode:'lines',x,y:n(rows,'SMA50'),line:{color:'#00e5ff',width:1.4},name:'SMA50',yaxis:'y'},{type:'scatter',mode:'lines',x,y:n(rows,'VWAP'),line:{color:'#ff00cc',width:1.4,dash:'dot'},name:'VWAP',yaxis:'y'},{type:'scatter',mode:'lines',x,y:n(rows,'BBUpper'),line:{color:'rgba(255,255,255,.28)',width:1},name:'BB Upper',yaxis:'y'},{type:'scatter',mode:'lines',x,y:n(rows,'BBLower'),line:{color:'rgba(255,255,255,.28)',width:1},fill:'tonexty',fillcolor:'rgba(255,255,255,.04)',name:'BB Lower',yaxis:'y'},{type:'bar',x,y:vol,marker:{color:'rgba(0,229,255,.22)'},name:'Volumen',yaxis:'y2'}],{...chartTheme,showlegend:true,legend:{orientation:'h',y:1.12},yaxis:{...chartTheme.yaxis,domain:[.28,1]},yaxis2:{...chartTheme.yaxis,domain:[0,.2]},hovermode:'x unified'},plotCfg); const base=close.find(v=>v!=null)||1, ret=close.map(v=>v==null?null:((v/base)-1)*100); $('secondary-title').textContent='Retorno acumulado'; Plotly.react('returns',[{type:'scatter',mode:'lines',x,y:ret,line:{color:'#00e5ff',width:2},fill:'tozeroy',fillcolor:'rgba(0,229,255,.08)'}],{...chartTheme,yaxis:{...chartTheme.yaxis,ticksuffix:'%'},hovermode:'x unified'},plotCfg); Plotly.react('rsi',[{type:'scatter',mode:'lines',x,y:n(rows,'RSI14'),line:{color:'#00ff99',width:2}}],{...chartTheme,shapes:[{type:'line',x0:x[0],x1:x[x.length-1],y0:70,y1:70,line:{color:'#ff4466',dash:'dot'}},{type:'line',x0:x[0],x1:x[x.length-1],y0:30,y1:30,line:{color:'#00e5ff',dash:'dot'}}],yaxis:{...chartTheme.yaxis,range:[0,100]}},plotCfg); Plotly.react('macd',[{type:'bar',x,y:n(rows,'MACDHist'),marker:{color:n(rows,'MACDHist').map(v=>v>=0?'rgba(0,255,153,.45)':'rgba(255,68,102,.45)')}},{type:'scatter',mode:'lines',x,y:n(rows,'MACD'),line:{color:'#00e5ff',width:2}},{type:'scatter',mode:'lines',x,y:n(rows,'MACDSignal'),line:{color:'#ff00cc',width:2}}],{...chartTheme,showlegend:true,legend:{orientation:'h',y:1.12}},plotCfg);}
function renderForecast(d){$('json').textContent=JSON.stringify(d,null,2); const m=d.metrics||{}; $('metrics').innerHTML=[['Estilo',d.style_label],['Motor',d.engine||'prophet'],['Modo forecast',d.forecast_mode||'—'],['Intervalo',d.interval],['Último',fmt(m.last)],['Final previsto',fmt(m.forecast_final)],['Cambio previsto',pctRaw(m.forecast_change_pct)],['Latencia ms',d.latency_ms]].map(([k,v])=>`<div class="api-metric"><span>${k}</span><b>${v??'—'}</b></div>`).join(''); const strip=$('forecastStrip'), dir=(m.forecast_change_pct??0)>=0?'forecast-up':'forecast-dn'; strip.style.display='grid'; strip.innerHTML=`<div class="forecast-hero"><span>Escenario ${d.style_label}</span><strong class="${dir}">${pctRaw(m.forecast_change_pct)}</strong><span>${fmt(m.last)} → ${fmt(m.forecast_final)}</span></div>`+d.forecast.map((r,i)=>`<div class="forecast-step"><span>+${i+1} paso${i?'s':''} <em class="future-chip">futuro</em></span><b>${fmt(r.yhat)}</b><div class="forecast-range">${fmt(r.yhat_lower)} – ${fmt(r.yhat_upper)}</div></div>`).join(''); const hx=d.history.map(r=>r.ds),hy=d.history.map(r=>+r.y),fx=d.forecast.map(r=>r.ds),fy=d.forecast.map(r=>+r.yhat),lo=d.forecast.map(r=>+r.yhat_lower),hi=d.forecast.map(r=>+r.yhat_upper); $('secondary-title').textContent=d.engine==='lstm_gpu'?'Predicción LSTM GPU':'Predicción Prophet'; Plotly.react('returns',[{type:'scatter',mode:'lines',x:hx,y:hy,line:{color:'#00e5ff',width:2},name:'Histórico'},{type:'scatter',mode:'lines',x:[hx[hx.length-1],...fx],y:[hy[hy.length-1],...fy],line:{color:'#f6c344',width:3},name:'Forecast'},{type:'scatter',mode:'lines',x:fx,y:hi,line:{color:'rgba(246,195,68,.18)'},name:'Superior'},{type:'scatter',mode:'lines',x:fx,y:lo,fill:'tonexty',fillcolor:'rgba(246,195,68,.14)',line:{color:'rgba(246,195,68,.18)'},name:'Inferior'}],{...chartTheme,showlegend:true,legend:{orientation:'h',y:1.12},hovermode:'x unified'},plotCfg); $('table-title').textContent='Trayectoria forecast'; $('table').className='forecast-table'; $('table').innerHTML='<thead><tr><th>Horizonte</th><th>Fecha</th><th>Predicción</th><th>Inferior</th><th>Superior</th></tr></thead><tbody>'+d.forecast.map((r,i)=>`<tr><td>+${i+1}</td><td>${r.ds}</td><td>${fmt(r.yhat)}</td><td>${fmt(r.yhat_lower)}</td><td>${fmt(r.yhat_upper)}</td></tr>`).join('')+'</tbody>';}
function renderPortfolio(d){$('json').textContent=JSON.stringify(d,null,2); const mx=d.max_sharpe.metrics,mn=d.min_variance.metrics,b=d.benchmark_metrics; $('metrics').innerHTML=[
  ['Motor',d.engine],['Solver',d.solver||'—'],['Activos',d.tickers.length],
  ['Sharpe',fmt(mx.sharpe)],['Sortino',fmt(mx.sortino)],['Alpha',pct(mx.alpha)],['Beta',fmt(mx.beta)],
  ['Volatilidad',pct(mx.annual_volatility)],['Drawdown',pct(mx.max_drawdown)],['VaR 95%',pct(mx.var_95_daily)],['CVaR 95%',pct(mx.cvar_95_daily)],
  ['Retorno acumulado',pct(mx.cumulative_return)],['CAGR',pct(mx.cagr)],['Mín varianza',pct(mn.annual_volatility)],
  ['Benchmark',d.benchmark],['Latencia ms',d.latency_ms]
].map(([k,v])=>`<div class="api-metric"><span>${k}</span><b>${v??'—'}</b></div>`).join(''); const c=d.cumulative||[], x=c.map(r=>r.date); $('secondary-title').textContent='Portafolio vs benchmark'; Plotly.react('returns',[{type:'scatter',mode:'lines',x,y:c.map(r=>r.max_sharpe*100),line:{color:'#f6c344',width:2.6},name:'Máx Sharpe'},{type:'scatter',mode:'lines',x,y:c.map(r=>r.min_variance*100),line:{color:'#00e5ff',width:2.2},name:'Mín varianza'},{type:'scatter',mode:'lines',x,y:c.map(r=>r.benchmark*100),line:{color:'#a9b7c6',width:2,dash:'dot'},name:d.benchmark}],{...chartTheme,showlegend:true,legend:{orientation:'h',y:1.12},yaxis:{...chartTheme.yaxis,ticksuffix:'%'},hovermode:'x unified'},plotCfg); Plotly.react('frontier',[{type:'scatter',mode:'markers',x:(d.cloud||[]).map(r=>r.risk*100),y:(d.cloud||[]).map(r=>r.return*100),marker:{color:'rgba(169,183,198,.22)',size:5},name:'Contexto Monte Carlo'},{type:'scatter',mode:'lines+markers',x:d.frontier.map(r=>r.risk*100),y:d.frontier.map(r=>r.return*100),line:{color:'#00ff99',width:3},marker:{color:d.frontier.map(r=>r.sharpe),colorscale:'Viridis',size:6,colorbar:{title:'Sharpe'}},name:'Frontera exacta'},{type:'scatter',mode:'markers',x:[mn.annual_volatility*100],y:[mn.annual_return*100],marker:{color:'#00e5ff',size:13,symbol:'diamond'},name:'Mín varianza'},{type:'scatter',mode:'markers',x:[mx.annual_volatility*100],y:[mx.annual_return*100],marker:{color:'#f6c344',size:14,symbol:'star'},name:'Máx Sharpe'}],{...chartTheme,showlegend:true,legend:{orientation:'h',y:1.12},xaxis:{...chartTheme.xaxis,title:'Riesgo anual %'},yaxis:{...chartTheme.yaxis,title:'Retorno anual %'}},plotCfg); const entries=d.tickers.map(t=>[t,Math.abs(d.max_sharpe.weights[t]||0)<1e-8?0:d.max_sharpe.weights[t]*100]); Plotly.react('weights',[{type:'bar',orientation:'h',y:entries.map(([k])=>k),x:entries.map(([,v])=>Number(v)),base:0,text:entries.map(([,v])=>v>0?`${v.toFixed(2)}%`:''),textposition:'outside',cliponaxis:false,marker:{color:entries.map(([,v])=>v>0?'#00ff99':'rgba(169,183,198,.18)')}}],{paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font:{color:'#a9b7c6',family:'Space Mono, monospace'},margin:{l:72,r:54,t:18,b:36},showlegend:false,xaxis:{type:'linear',range:[0,100],dtick:20,ticksuffix:'%',gridcolor:'rgba(255,255,255,.06)',autorange:false,zeroline:false},yaxis:{type:'category',automargin:true,gridcolor:'rgba(255,255,255,.06)'},hovermode:'y unified'},plotCfg); $('table-title').textContent='Asignación y métricas'; $('table').className='portfolio-table'; $('table').innerHTML='<thead><tr><th>Activo</th><th>Máx Sharpe</th><th>Mín Varianza</th></tr></thead><tbody>'+d.tickers.map(t=>`<tr><td>${t}</td><td>${pct(d.max_sharpe.weights[t])}</td><td>${pct(d.min_variance.weights[t])}</td></tr>`).join('')+`</tbody><tfoot><tr><th>Benchmark ${d.benchmark}</th><td colspan="2">${pct(b.cumulative_return)} retorno acumulado · Sharpe ${fmt(b.sharpe)}</td></tr></tfoot>`;}
function syncSections(e){const isForecast=e==='forecast/prophet'||e==='forecast/lstm', isPortfolio=e==='portfolio/markowitz', isMarket=e.includes('market'); $('forecastMode').disabled=e!=='forecast/prophet'; $('style').disabled=!isForecast; $('ticker').disabled=isPortfolio; $('interval').disabled=isPortfolio; $('period').disabled=isPortfolio; $('mode').disabled=!(e==='market'||isPortfolio); $('portfolioControls').style.display=isPortfolio?'block':'none'; $('marketCandles').style.display=isMarket?'block':'none'; $('marketIndicators').style.display=isMarket?'grid':'none'; $('secondaryChart').style.display=(isMarket||isForecast||isPortfolio)?'block':'none'; $('portfolioCharts').style.display=isPortfolio?'grid':'none'; if(!isForecast)$('forecastStrip').style.display='none';}
function render(d){const e=$('endpoint').value; syncSections(e); if(d.forecast)return renderForecast(d); if(d.max_sharpe&&d.min_variance)return renderPortfolio(d); return renderMarket(d);}
